# Generated by Django 3.1.6 on 2021-02-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_url', models.CharField(max_length=250)),
                ('job_source', models.CharField(max_length=100)),
            ],
        ),
    ]
