# Generated by Django 3.1.6 on 2021-02-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_url', models.CharField(max_length=800)),
                ('job_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='JobData',
        ),
    ]
